language: objective-c
os: osx
osx_image: xcode10.1
rvm:
- 2.2         #see before_install for getting RVM stable.

env:
  global: 
    - UNITY_PROJECT_PATH="IPTech-Coroutines" 
    - DOWNLOAD_CACHE="unity_download_cache"
    - PACKAGES="Assets/IPTech.Coroutines Assets/IPTech.Coroutines.Examples"

cache:
  directories:
    - $DOWNLOAD_CACHE

before_install:
- chmod a+x ./travis-build/*.sh

install:
- ./travis-build/install-unity.sh

script:
- ./travis-build/run-tests.sh

deploy:
  provider: script
  script: "./travis-build/publish-packages.sh"
  on:
    tags: true
    branch: master
